//This file is generated by bin/hook.js
var _ = require('underscore');
module.exports = {
 'p2phlsstats': _.template('<p>dasdasd</p>'),
  CSS: {
    'testcore': '.container[data-container]{background:red;} body{background:red;}',
  }
};
